version: 0.2

phases:
  install:
    commands:

  pre_build:
    commands:

  build:
    commands:
      - aws codepipeline get-job-details
 


artifacts:
  files:
    - "**/*"
  name: myname-$AWS_REGION 



