version: 0.2

phases:
  install:
    commands:

  pre_build:
    commands:

  build:
    commands:
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION

artifacts:
  files:
    - "**/*"
  name: myname-$AWS_REGION 



