version: 0.2

phases:
  install:
    commands:

  pre_build:
    commands:

  build:
    commands:
      - echo $Message
      - chmod +x suitexecute.sh
      - ./suitexecute.sh

artifacts:
  files:
    - "**/*"
  name: myname-$AWS_REGION 

