version: 0.2

phases:
  install:
    commands:

  pre_build:
    commands:

  build:
    commands:
      - aws codepipeline list-action-executions --pipeline-name gui-test

artifacts:
  files:
    - "**/*"
  name: myname-$AWS_REGION 



