version: 0.2

phases:
  install:
    commands:

  pre_build:
    commands:

  build:
    commands:
      - echo ${SourceVariables.CommitMessage}

artifacts:
  files:
    - "**/*"
  name: myname-$AWS_REGION 



