version: 0.2

phases:
  install:
    commands:

  pre_build:
    commands:

  build:
    commands:
      - git clone https://github.com/Coder293/devicefarm.git
      - git log
 


artifacts:
  files:
    - "**/*"
  name: myname-$AWS_REGION 



